In [53]:
import numpy as np

In [54]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,4,9]])

B = np.matrix([[1,2,4],
               [7,1,3],
               [9,4,3]])

In [55]:
#inverse
inv_A = np.linalg.inv(A)

In [56]:
#solve linear equations
X = np.linalg.inv(A).dot(B)

In [57]:
#solve linear equations 2
X = np.linalg.solve(A,B)

In [58]:
#transpose
np.transpose(A)

array([[1, 4, 7],
       [2, 5, 4],
       [3, 6, 9]])

In [59]:
#determinant
np.linalg.det(A)

-23.999999999999993

In [60]:
#change basis
vec_new = np.linalg.inv(A).dot(B)

In [61]:
#projection of one vector on another
u = np.array([1, 1, 1])
v = np.array([1, 2, 2])

# Task: Project vector u on vector v
# finding norm of the vector v

v_norm = np.sqrt(sum(v**2))

# Apply the formula as mentioned above
# for projecting a vector onto another vector
# find dot product using np.dot()
proj_of_u_on_v = (np.dot(u, v)/v_norm**2)*v
print("Projection of Vector u on Vector v is: ", proj_of_u_on_v)

Projection of Vector u on Vector v is:  [0.55555556 1.11111111 1.11111111]


In [62]:
# vector u 
u = np.array([2, 5, 8])

# vector n: n is orthogonal vector to Plane P
n = np.array([1, 1, 7])

# Task: Project vector u on Plane P

# finding norm of the vector n 
n_norm = np.sqrt(sum(n**2))

# Apply the formula as mentioned above
# for projecting a vector onto the orthogonal vector n
# find dot product using np.dot()
proj_of_u_on_n = (np.dot(u, n)/n_norm**2)*n

# subtract proj_of_u_on_n from u: 
# this is the projection of u on Plane P
print("Projection of Vector u on Plane P is: ", u - proj_of_u_on_n)

Projection of Vector u on Plane P is:  [ 0.76470588  3.76470588 -0.64705882]


In [63]:
#Eigenvectors
np.linalg.eig(A)

(array([14.47075914, -1.05011946,  1.57936032]),
 array([[-0.25792927, -0.81244376, -0.09396151],
        [-0.59244793, -0.03972377, -0.83664891],
        [-0.76320242,  0.58168477,  0.53962008]]))